# Generated by Django 3.0.3 on 2020-03-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20200305_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefun',
            new_name='image',
        ),
    ]
